### ISSUE TITLE
Be able to set one password per user 

### ISSUE THREAD

**Issue by poquirion** [ComputeCanada/magic_castle#107]
A repeated request from bioinfo workshop teacher is to be able to set one pw per user to avoid having two students accidentally using the same account.

perhaps this would be a reasonable interface

guest_passwd = "" # keep current behaviour

guest_passwd = [] # one pw per user

or

guest_passwd { 
object({
one_per_user = bool # if false only one pw is generated
password = list(string) # if set to [""] then the list  is generated automatically 
})
}

**Comment by cmd-ntrf** [comment]
I recognize that sharing a password with all guest accounts is not ideal. I also think it would become increasingly difficult to configure and distribute the passwords as the number of workshop attendees grows.

A better solution would be to ask for participants to create their own account on the cluster. I have done a successful account creation test with [Mokey](https://github.com/ubccr/mokey). Participants would be able to define their own username and password using an web form to which link would be shared at the beginning of the workshop.

The elements missing from Mokey are the home directory and Slurm account creation, so some development is required, but I think it would worth it.
