### ISSUE TITLE
DNS settings for FSx integration

### ISSUE THREAD

**Issue by verdurin** [ComputeCanada/magic_castle#109]
I've been testing Amazon FSx and one of the requirements for mounting such filesystems is the use of Amazon DNS, to resolve the NID. Otherwise you see errors like this:
```
sudo mount -t lustre -o noatime,flock fs-<filesystem-id>fsx.eu-central-1.amazonaws.com@tcp:/<mount point> /fsx
mount.lustre: Can't parse NID 'fs-<filesystem-id>fsx.eu-central-1.amazonaws.com@tcp:/<mount point>'
```

https://docs.aws.amazon.com/fsx/latest/LustreGuide/troubleshooting.html#mount-fails-dns-name

This suggests that the problem is that MC instances use the FreeIPA resolver, not Amazon.
Could the Amazon DNS be added as one of the resolvers within FreeIPA?

When I have tested with a manually deployed instance in the same VPC as the FSx filesystem, I have been able to mount FSx successfully.

**Comment by cmd-ntrf** [comment]
The instances `resolv.conf` is configured to use the FreeIPA DNS as a nameserver first, but it also keeps the nameservers from AWS (i.e.: 10.0.0.2).

To activate AWS DNS in a VPC, there is two settings : DNS Support and DNS Hostnames.
https://docs.aws.amazon.com/vpc/latest/userguide/vpc-dns.html#vpc-dns-updating

By default, Terraform aws_vpc resources is configured with the flag `enable_dns_hostnames` to false.
https://www.terraform.io/docs/providers/aws/r/vpc.html#argument-reference

Adding enable_dns_hostnames to the aws_vpc ressource in [aws/infrastructure.tf](https://github.com/ComputeCanada/magic_castle/blob/master/aws/infrastructure.tf#L28) might be enough.

After enabling DNS Hostnames manually for the VPC and creating a Lustre filesystem, I was able to resolve the filesystem hostname with dig without any change to resolv.conf:
`dig fs-<id>.fsx.ca-central-1.amazonaws.com`

It took a few minutes before dig could resolv. I was then able to mount the filesystem.

I will try again with `enable_dns_hostnames` set to true in aws_vpc.

**Comment by verdurin** [comment]
Thanks for testing. I was concerned about the effect of cluster-internal name resolution if I changed VPC settings.

Sounds like that shouldn't be a problem.

**Comment by cmd-ntrf** [comment]
After setting `enable_dns_hostnames = true` in aws_vpc and creating a new cluster, I was able to resolv a new lustre filesystem hostname, and the internal dns and hostnames work as before.

I will commit the dns hostname enabling in AWS.

**Comment by verdurin** [comment]
Great, thanks a lot.

**Comment by cmd-ntrf** [comment]
Done.
