### ISSUE TITLE
Value for ssh_private_key in the dns module

### ISSUE THREAD

**Issue by afernandezody** [ComputeCanada/magic_castle#113]
Hello,
I'm trying to register the domain name for a GCP cluster with GCP (everything is GCP as I'm also deploying from a small instance). I uncommented the 2nd module dns (here it seems that a comment line might be missing).  Which is the value for the variable ssh_private_key? In the example, it's set to module.openstack.ssh_private_key but that doesn't work. 
```
$terraform plan
Error: Reference to undeclared module

  on main.tf line 69, in module "dns":
  69:    ssh_private_key  = module.openstack.ssh_private_key

No module call named "openstack" is declared in the root module.
```

I tried the obvious modification and set the variable to module.gcp.ssh_private_key, but got
```
$terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

module.gcp.data.http.hieradata_template: Refreshing state...
module.dns.data.google_dns_managed_zone.domain: Refreshing state...
module.gcp.data.google_compute_zones.available: Refreshing state...

Error: googleapi: Error 403: Request had insufficient authentication scopes.
More details:
Reason: insufficientPermissions, Message: Insufficient Permission


  on gcp/infrastructure.tf line 6, in data "google_compute_zones" "available":
   6: data "google_compute_zones" "available" {


Error: googleapi: Error 403: Request had insufficient authentication scopes.
More details:
Reason: insufficientPermissions, Message: Insufficient Permission

  on .terraform/modules/dns/dns/gcloud/main.tf line 5, in data "google_dns_managed_zone" "domain":
   5: data "google_dns_managed_zone" "domain" {

```

Not sure if something else must be defined earlier or OAuth 2.0 keys are necessary . Thanks.

**Comment by afernandezody** [comment]
I tried to follow the directions at README (/dns/gcloud) and exported GOOGLE_CREDENTIALS & GCE_SERVICE_ACCOUNT_FILE with the chosen json file as one of my OAuth2 credentials. Then, when TF tries to figure out the plan, there is a new error that reads:
```
Error: Unable to parse credentials from '{"installed":{"client_id":"42301 ... ,"redirect_uris":["urn:ietf:wg:oauth:2.0:oob","http://localhost"]}}': missing 'type' field in credentials

  on gcp/infrastructure.tf line 1, in provider "google":
   1: provider "google" {

```
I'm still unsure if this is the right approach but, if this is so, is there any specific fashion that the credentials should be generated?

**Comment by cmd-ntrf** [comment]
> Hello,
> I'm trying to register the domain name for a GCP cluster with GCP (everything is GCP as I'm also deploying from a small instance). I uncommented the 2nd module dns (here it seems that a comment line might be missing). Which is the value for the variable ssh_private_key? In the example, it's set to module.openstack.ssh_private_key but that doesn't work.

> 
> ```
> $terraform plan
> Error: Reference to undeclared module
> 
>   on main.tf line 69, in module "dns":
>   69:    ssh_private_key  = module.openstack.ssh_private_key
> 
> No module call named "openstack" is declared in the root module.
> ```
> 
> I tried the obvious modification and set the variable to module.gcp.ssh_private_key, but got

You are right, it should have been module.gcp.ssh_private_key. Thanks for reporting this. I will fix the examples.

> 
> ```
> $terraform plan
> Refreshing Terraform state in-memory prior to plan...
> The refreshed state will be used to calculate this plan, but will not be
> persisted to local or remote state storage.
> 
> module.gcp.data.http.hieradata_template: Refreshing state...
> module.dns.data.google_dns_managed_zone.domain: Refreshing state...
> module.gcp.data.google_compute_zones.available: Refreshing state...
> 
> Error: googleapi: Error 403: Request had insufficient authentication scopes.
> More details:
> Reason: insufficientPermissions, Message: Insufficient Permission
> 
> 
>   on gcp/infrastructure.tf line 6, in data "google_compute_zones" "available":
>    6: data "google_compute_zones" "available" {
> 
> 
> Error: googleapi: Error 403: Request had insufficient authentication scopes.
> More details:
> Reason: insufficientPermissions, Message: Insufficient Permission
> 
>   on .terraform/modules/dns/dns/gcloud/main.tf line 5, in data "google_dns_managed_zone" "domain":
>    5: data "google_dns_managed_zone" "domain" {
> ```
> 

This means the account you are using does not have the right to add a DNS entry in Google DNS. Is the domain you defined in Magic Castle currently registered in Google DNS? Can you add records manually using Google Cloud dashboard to this domain?
