### ISSUE TITLE
Missing home directory for users added after cluster creation

### ISSUE THREAD

**Issue by verdurin** [ComputeCanada/magic_castle#114]
I have followed the instructions at https://github.com/ComputeCanada/magic_castle/tree/master/docs#103-add-a-user-account to add users.

However, it appears no home directory is created for them either at account creation time, or when they login for the first time.

**Comment by verdurin** [comment]
This is related somewhat to #107 I suppose.

**Comment by cmd-ntrf** [comment]
The home folder has to be created manually after the account is created. I have been working in the past few months on a new script to create accounts that would handle account creation and its related personal folders, but I am not quite satisfied with the results as we speak.

**Comment by cmd-ntrf** [comment]
Fixed in release 9.1.
