### ISSUE TITLE
Description field for security group rules on AWS

### ISSUE THREAD

**Issue by verdurin** [ComputeCanada/magic_castle#115]
For cases where multiple custom security group entries are being added, it would be helpful if `description` field support could be added.

This makes it a lot easier when checking in the Console that the correct rules are present.

**Comment by cmd-ntrf** [comment]
You are suggesting we add description to each individual rule, like SSH or Globus?

**Comment by verdurin** [comment]
Yes. In our case, we have multiple SSH rules so it's helpful to be able to differentiate them easily.

**Comment by cmd-ntrf** [comment]
What should appear in the description except for SSH for example? The name of the cluster?

**Comment by verdurin** [comment]
It should be an optional field that I can specify in `main.tf`. 

For example, a particular SSH rule might be for "VPN group 2" etc.

**Comment by cmd-ntrf** [comment]
Oh you would like to add a rule to the security group AND add a description to that rule?

**Comment by verdurin** [comment]
Yes.

**Comment by cmd-ntrf** [comment]
Fix in #247
