### ISSUE TITLE
Id resolution problem on the login node.

### ISSUE THREAD

**Issue by poquirion** [ComputeCanada/magic_castle#119]
I have seen that on `/home` and `/scratch`
I added a file with the root user on the mgmt1 node, chaged the uid:gid and  then it cannot be  resolved on the login node

```
-bash-4.2$ ls -asl 
ls: cannot access '.bashrc': Permission denied
total 4
0 drwxr-xr-x.  2 user38 user38   40 Oct 13 15:18 .
4 drwxr-xr-x. 47 root   root   4096 Oct 13 15:16 ..
? -??????????  ? ?      ?         ?            ? .bashrc
0 lrwxrwxrwx.  1 user38 user38   24 Oct 13 15:17 .lmodrc.lua -> /scratch/user35/modulerc
-bash-4.2$ salloc 
salloc: Granted job allocation 14
salloc: Waiting for resource configuration
salloc: Nodes node1 are ready for job
[user38@node1 ~]$ ls -als 
total 8
0 drwxr-xr-x.  2 user38 user38   40 Oct 13 15:18 .
4 drwxr-xr-x. 47 root   root   4096 Oct 13 15:16 ..
4 -rw-r--r--.  1 user38 user38  329 Oct 13 15:18 .bashrc
0 lrwxrwxrwx.  1 user38 user38   24 Oct 13 15:17 .lmodrc.lua -> /scratch/user35/modulerc
```

has you see, here the bashrc file is only resolved when on a compute node.

I when around that problem for the modulerc file by creating it with a normal user (one of the TA account), since a shared folder was not recognized on the login node when created be the root user on mgmt1.

**Comment by poquirion** [comment]
wow, comming back from the compute node, and the bash_history file too was not resolvable since it was created on the compute node.
```salloc: Relinquishing job allocation 14
-bash-4.2$ ls -sla 
ls: cannot access '.bashrc': Permission denied
ls: cannot access '.bash_history': Permission denied
total 4
0 drwxr-xr-x.  2 user38 user38   61 Oct 13 15:40 .
4 drwxr-xr-x. 47 root   root   4096 Oct 13 15:16 ..
? -??????????  ? ?      ?         ?            ? .bash_history
? -??????????  ? ?      ?         ?            ? .bashrc
0 lrwxrwxrwx.  1 user38 user38   24 Oct 13 15:17 .lmodrc.lua -> /scratch/user35/modulerc
-bash-4.2$ id
```

**Comment by cmd-ntrf** [comment]
The SELinux context of files with question mark is wrong. They appear on the compute node during a job because the SELinux context of a job is `unconstrained` since for now slurmd run as root and fork a user.
