### ISSUE TITLE
similar cloud HPC project

### ISSUE THREAD

**Issue by rptaylor** [ComputeCanada/magic_castle#121]
Some info for the list of similar projects. StackHPC has similar activities.
https://www.stackhpc.com/

Here is an Ansible role to deploy a SLURM "OpenHPC" cluster, with login node etc.
https://github.com/stackhpc/ansible-role-openhpc

They use Ironic to deploy bare metal HPC nodes on Openstack.

**Comment by cmd-ntrf** [comment]
Thanks!
I added the repo to the reference list.
