### ISSUE TITLE
Allow use of image_id when specifying Azure image

### ISSUE THREAD

**Issue by ocaisa** [ComputeCanada/magic_castle#127]
Currently it doesn't seem to be possible to specify an image to use with Azure. This would require supporting the `source_image_id` of `azurerm_linux_virtual_machine`, but I don't think you can have both, it's either `source_image_id` or `source_image_reference`. Is it possible to have the logic in terraform that if `var.image["id"]` exists you set one and if not you use the other?

**Comment by ocaisa** [comment]
The reason I'm looking at this is I would like to configure Azure to use their infiniband nodes. Someone from Azure has given me a custom CentOS7 image that has the infiniband support baked in. I tested it and things seem to work fine. One piece of advice I was given though was:
```
In order for the two VMs to be in the same IB fabric you have to first create an availability set with:

$ az vm availability-set create --name <as_name> --resource-group <rg-name> --location eastus --platform-fault-domain-count 1 --platform-update-domain-count 1

Then, when you create each VM, assign them to the availability set with the following option:

$ az vm create […] --availability-set <as_name>

Also do not forget to put them on the same network and subnet.
```
It doesn't look like `availability_set_id` is currently being used/configured. I'm not sure what the impact of this would be, but it seems like a reasonable thing to do by default for the execution nodes.

**Comment by cmd-ntrf** [comment]
For the image, we could probably replace `source_image_reference` by `source_image_id `. To do it, we would need to determine the image id based on the image reference map first, then provide this id to `source_image_id`.

There is an Azure data source named `azurerm_platform_image` that appears to do that exactly:
```
data "azurerm_platform_image" "example" {
  location  = "West Europe"
  publisher = "Canonical"
  offer     = "UbuntuServer"
  sku       = "16.04-LTS"
}

output "id" {
  value = data.azurerm_platform_image.example.id
}
```
Ref: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/platform_image

Branch [`azure_image`](https://github.com/ComputeCanada/magic_castle/tree/azure_image) implements this change. I just need to test it to confirm it works.

**Comment by cmd-ntrf** [comment]
The preceding solution does not work because of a limitation in Azure.
https://github.com/terraform-providers/terraform-provider-azurerm/issues/6745#issuecomment-626134956
> the service does not accept an ID from a platform image.

I will try to find another hack.

**Comment by cmd-ntrf** [comment]
In branch `azure_image`, I have a fix to support both a map of image information and an image id.

If `var.image` is a map, `source_image_id` is set to null and ignore. `source_image_reference` is now a dynamic block, so if `var.image` is a string, it becomes empty and is not considered when building the instances.

@ocaisa : I don't have an example of an image id to test this. Could you give it a try?

**Comment by ocaisa** [comment]
@cmd-ntrf I took this for a test drive and it worked for me.

In the docs, it might be useful to tell people that they can list their custom images on Azure with `az image builder list` and extract the `"id"` for the image they want to use from there.

I also have the steps used to create the image with OFED support, is that something we might want to consider supporting with puppet instead? It might be a bit brittle though...

**Comment by ocaisa** [comment]
Should you also add `source_image_id` to 
```
  lifecycle {
    ignore_changes = [
      source_image_reference
    ]
  }
```
in each case?
(Full disclosure: I don't know what that does)
