### ISSUE TITLE
Supporting spot instances on AWS/Azure

### ISSUE THREAD

**Issue by ocaisa** [ComputeCanada/magic_castle#134]
Spot instances are *significantly* cheaper on AWS and Azure, and supporting them could mean much larger clusters for the same cost. 

For Azure, I found [something on stackoverflow](https://stackoverflow.com/questions/63138023/how-do-i-request-azure-spot-instances-using-terraform-in-a-virtual-machine-scal) that show the additional variables you need to set.

For AWS, you need to request an [AWS spot instance](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/spot_instance_request) which includes being able to set `block_duration_minutes`of up to six hours. This would be pretty good for compute nodes.

**Comment by cmd-ntrf** [comment]
With the next interface, it would be possible to add `spot` to the list of tags of an instance type and use `aws_spot_instance_request` instead of `aws_instance` to create these instances.

**Comment by cmd-ntrf** [comment]
I made a PR draft for this request. It currently works for AWS by adding a `spot` tag to the list of tags.
