### ISSUE TITLE
SSL certificate creation problem

### ISSUE THREAD

**Issue by ocaisa** [ComputeCanada/magic_castle#137]
While this has worked in the past, and as recently as last week, I currently hit a certificate creation error when trying to bring up a new cluster:
```
Error: error creating certificate: error: one or more domains had a problem:
[*.jacket.learnhpc.eu] time limit exceeded: last error: read udp [2a02:2e02:998e:9300:853b:8fa4:8f43:d7c1]:46020->[2a06:98c1:50::ac40:23c4]:53: i/o timeout
[jacket.learnhpc.eu] time limit exceeded: last error: read udp [2a02:2e02:998e:9300:853b:8fa4:8f43:d7c1]:52201->[2a06:98c1:50::ac40:23c4]:53: i/o timeout
```
On initialisation terraform has given a warning which is perhaps related:
```
Warning: Additional provider information from registry

The remote registry returned warnings for
registry.terraform.io/terraform-providers/acme:
- For users on Terraform 0.13 or greater, this provider has moved to
vancluever/acme. Please update your source in required_providers.

```

**Comment by ocaisa** [comment]
This looks like it could be an issue with our OpenStack provider. The ports accessible on the servers are extremely limited, does the certificate creation involve communicating with "unusual" ports?

**Comment by cmd-ntrf** [comment]
The certificate creation is done on the computer executing `terraform apply`. Based on the log, it looks terraform is trying to communicate with the DNS provider or ACME over IPV6.

**Comment by ocaisa** [comment]
Confirmed, forcing my local machine to prefer ipv4 seems to make things work as expected
