### ISSUE TITLE
Details required of how to create SSHFP DNS records

### ISSUE THREAD

**Issue by verdurin** [ComputeCanada/magic_castle#140]
In the section listing how to create DNS records manually, where Google and CloudFlare aren't available, it would be helpful to add details of how to create the SSHFP records given that they depend on other outputs.

Cf. https://github.com/ComputeCanada/magic_castle/blob/d287daef62bd90df3aabc5dac34418ede7de4724/dns/record_generator/main.tf#L67

**Comment by cmd-ntrf** [comment]
Good point.

We could also look for a way to display a list of records that needs to be added manually when neither cloudflare or google is used, either by showing it on screen after `terraform apply` or create a text file with the records to add.

**Comment by cmd-ntrf** [comment]
@verdurin : could check if PR https://github.com/ComputeCanada/magic_castle/pull/143 would answer your request?

**Comment by verdurin** [comment]
@cmd-ntrf : yes, that looks good, thanks.

**Comment by cmd-ntrf** [comment]
Fixed by PR #143
