### ISSUE TITLE
Using multi-user cloudflare account

### ISSUE THREAD

**Issue by mboisson** [ComputeCanada/magic_castle#16]
With the cloudflare provider 2.x, it is possible to use specific keys to configure the DNS. The permissions required for a key are : 

Cloudflare Account :  Account Settings:Read
Zone:  Zone Settings:Read, Zone:Read, DNS:Edit

One can then define the following environment variables : 
export CLOUDFLARE_API_TOKEN="TOKEN GOES HERE"
export CLOUDFLARE_ZONE_API_TOKEN=$CLOUDFLARE_API_TOKEN
export CLOUDFLARE_DNS_API_TOKEN=$CLOUDFLARE_API_TOKEN

**Comment by cmd-ntrf** [comment]
Commit 5fd7f5f7a6b1536ecfd13378d276ef83192f9b4d adds documentation in README.md with how to configure an API token with the right permissions.

**Comment by cmd-ntrf** [comment]
I have reviewed the export as suggested in commit dd4a3b5.
.
