### ISSUE TITLE
Upstream bug - Google DNS: expected type to be one of [A AAAA CAA CNAME MX NAPTR NS PTR SOA SPF SRV TLSA TXT], got SSHFP

### ISSUE THREAD

**Issue by consideRatio** [ComputeCanada/magic_castle#165]
With the following configuration in `main.tf` part of version `11.0` and using terraform 0.15.1 I got the following error.

```
╷
│ Error: expected type to be one of [A AAAA CAA CNAME MX NAPTR NS PTR SOA SPF SRV TLSA TXT], got SSHFP
│ 
│   with module.dns.google_dns_record_set.records[7],
│   on dns/gcloud/main.tf line 22, in resource "google_dns_record_set" "records":
│   22:   type         = module.record_generator.records[count.index].type
│ 
╵
╷
│ Error: expected type to be one of [A AAAA CAA CNAME MX NAPTR NS PTR SOA SPF SRV TLSA TXT], got SSHFP
│ 
│   with module.dns.google_dns_record_set.records[6],
│   on dns/gcloud/main.tf line 22, in resource "google_dns_record_set" "records":
│   22:   type         = module.record_generator.records[count.index].type
│ 
╵
```

Looking into it, I've tracked it to be a bug unrelated to this repo's content and fixed upstream by the google terraform provider in a [PR that is merged](https://github.com/hashicorp/terraform-provider-google/pull/8919/files) and released as part of [v3.66.0](https://github.com/hashicorp/terraform-provider-google/releases/tag/v3.66.0).

Running `terraform version` I get...

```
terraform version    
Terraform v0.15.1
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v2.20.0
+ provider registry.terraform.io/hashicorp/aws v3.37.0
+ provider registry.terraform.io/hashicorp/external v2.1.0
+ provider registry.terraform.io/hashicorp/google v3.64.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/tls v3.1.0
+ provider registry.terraform.io/vancluever/acme v2.4.0
```

From this I conclude that the unreleased terraform 0.15.2 or higher will be required for full functionality with Google DNS.

**Comment by consideRatio** [comment]
I learned that I can use `terraform init -upgrade` to upgrade the provider versions which probably were installed when I ran `terraform init` the first time or similar.

To verify I got a new version of the google provider that needed an update, I ran `terraform version` again and could conclude it was indeed updated.

```
terraform version      
Terraform v0.15.1
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v2.20.0
+ provider registry.terraform.io/hashicorp/aws v3.38.0
+ provider registry.terraform.io/hashicorp/external v2.1.0
+ provider registry.terraform.io/hashicorp/google v3.66.1
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/tls v3.1.0
+ provider registry.terraform.io/vancluever/acme v2.4.0
```

I'll go ahead and close this issue directly as I don't see an action point associated with it but it could probably be findable by googling on the error for others now.

**Comment by cmd-ntrf** [comment]
Wow that was fast!
Thanks for leaving a trace here.
