### ISSUE TITLE
Changed `os_floating_ips` input type from list to map

### ISSUE THREAD

**Issue by ocaisa** [ComputeCanada/magic_castle#178]
While migrating to 11.0, I need to update `os_floating_ips` from a list to a map, but it is unclear to me what the mapping should be, can you give an example (and maybe include that example in the docs)?

**Comment by cmd-ntrf** [comment]
I have revised the `os_floating_ips` documentation and added an example.
https://github.com/ComputeCanada/magic_castle/commit/ec4983462552b23b93b0ca704cc74570cad3459e?short_path=0b5ca11#diff-0b5ca119d2be595aa307d34512d9679e49186307ef94201e4b3dfa079aa89938

Let met know if it is clearer.

**Comment by ocaisa** [comment]
Perfect, thanks
