### ISSUE TITLE
(documentation) openrc v3 required for CC OpenStack cloud

### ISSUE THREAD

**Issue by jflandry** [ComputeCanada/magic_castle#18]
magic_castle/openstack/README.md

Step 1 is
Download your project openrc file from the OpenStack Access and security section.

The v2 openrc does not work with the authentication method in use, there should be a specific mention to download the v3 openrc file.

This causes the following error during a terraform plan:

```module.openstack.data.http.hieradata_template: Refreshing state...

Error: You must provide exactly one of DomainID or DomainName to
authenticate by Username

  on openstack/infrastructure.tf line 1, in provider "openstack":
   1: provider "openstack" {```

**Comment by cmd-ntrf** [comment]
Fixed by commit 73b79a9.
Thanks!
