### ISSUE TITLE
Ability to provision multiple authorized ssh keys for the centos account

### ISSUE THREAD

**Issue by mboisson** [ComputeCanada/magic_castle#20]
When creating the cluster, it seems that there is a single key that is copied onto each node, for centos. Since centos' home folder is not on a shared filesystem, it is a bit of a hassle to send the key to all nodes. It would be good if we could provision the nodes with more than one ssh key for the centos account.

**Comment by cmd-ntrf** [comment]
It is already possible.

The `public_keys` variable is a list. Add the keys to the list, either directly as a direct, or using the `file` function as in the example.

**Comment by mboisson** [comment]
Oops, my bad. Sorry for the noise.
