### ISSUE TITLE
OVH: Issues with SSH after provisioning a Magic Castle cluster

### ISSUE THREAD

**Issue by p-1603** [ComputeCanada/magic_castle#215]
I am using the latest tarball for Magic Castle on OVH cloud, and find the following:

- I can set up the credentials and create a custom image as described in the main documentation.
- I can use `terraform apply` to create the cluster, with no errors reported.
- I can sign into the sudoer, admin and guest accounts on the login and management nodes immediately after cluster creation.
- Within about twenty minutes, trying to SSH into the sudoer account results in a demand for a password, which does not exist.
- The password for the admin account no longer also stops working.

I'm guessing something changes during the provision described [here](https://github.com/ComputeCanada/magic_castle/tree/main/docs#8-deployment), but am unable to work out what exactly is going wrong. Would someone be able to help me work a fix?

Extra Notes:
- OVH base images now appear to have SELinux enabled by default, in contrast to what is described [here](https://github.com/ComputeCanada/magic_castle/tree/main/docs#8-deployment).
- In many regions the Stein release of Openstack is still being used, meaning that the `port_security_enabled` option must be set to `true` in `network-1.tf` in order for the cluster to build successfully. This is explained by OVH [here](https://docs.ovh.com/gb/en/public-cloud/firewall_security_pci/#different-behaviour-depending-on-regions).

**Comment by ocaisa** [comment]
I think this may have been fixed with https://github.com/ComputeCanada/puppet-magic_castle/pull/198

**Comment by ocaisa** [comment]
Hmm, no, that is too old, I must be wrong

**Comment by p-1603** [comment]
Here we go. I've changed the cluster name, image, SSH key field, and the node flavours.

```
terraform {
  required_version = ">= 1.1.0"
}

module "ovh" {
  source         = "./ovh"
  config_git_url = "https://github.com/ComputeCanada/puppet-magic_castle.git"
  config_version = "11.9.3"

  cluster_name = "treble"
  domain       = "calculquebec.cloud"
  image        = "My Custom Image"

  instances = {
    mgmt   = { type = "b2-7", tags = ["puppet", "mgmt", "nfs"], count = 1 }
    login  = { type = "b2-7", tags = ["login", "public", "proxy"], count = 1 }
    node   = { type = "b2-7", tags = ["node"], count = 1 }
  }

  volumes = {
    nfs = {
      home     = { size = 10 }
      project  = { size = 50 }
      scratch  = { size = 50 }
    }
  }
  public_keys = [file("~/.ssh/id_ed25519_23022022.pub")]

  nb_users     = 10
  # Shared password, randomly chosen if blank
  guest_passwd = ""

}

output "accounts" {
  value = module.ovh.accounts
}

output "public_ip" {
  value = module.ovh.public_ip
}

## Uncomment to register your domain name with CloudFlare
# module "dns" {
#   source           = "./dns/cloudflare"
#   email            = "you@example.com"
#   name             = module.ovh.cluster_name
#   domain           = module.ovh.domain
#   public_instances = module.ovh.public_instances
#   ssh_private_key  = module.ovh.ssh_private_key
#   sudoer_username  = module.ovh.accounts.sudoer.username
# }

## Uncomment to register your domain name with Google Cloud
# module "dns" {
#   source           = "./dns/gcloud"
#   email            = "you@example.com"
#   project          = "your-project-id"
#   zone_name        = "you-zone-name"
#   name             = module.ovh.cluster_name
#   domain           = module.ovh.domain
#   public_instances = module.ovh.public_instances
#   ssh_private_key  = module.ovh.ssh_private_key
#   sudoer_username  = module.ovh.accounts.sudoer.username
# }

# output "hostnames" {
#   value = module.dns.hostnames
# }
```

This is using version 11.9.3, from [here](https://github.com/ComputeCanada/magic_castle/releases/tag/11.9.3).

**Comment by cmd-ntrf** [comment]
The problem could be related to your custom image.

The sudoer account is created first through the cloud-init yaml file provide to each instance:
https://github.com/ComputeCanada/magic_castle/blob/main/common/instance_config/puppet.yaml#L7
As you can see on line 7, this where we first defined the sudoer account and add the ssh keys to its authorized_keys file.

Potential problem here with a custom image: it is possible that the sudoer account `centos` is created by your custom image, and by default this account home folder will be placed in `/home/centos`. If it is the case, the cloud-init will not move the home folder to `/centos` but it will define the authorized_keys file. When later on, puppet mounts the NFS file system of top of `/home`, the `/home/centos` account will no longer be visible and you would get a password prompt when trying to connect with SSH.

The solution here would be to either
- a. completely remove the sudoer account when creating your custom image
- b. move its home folder to `/centos`
- c. define a different sudoer username in your main.tf to lift the ambiguity: https://github.com/ComputeCanada/magic_castle/tree/main/docs#412-sudoer_username-optional

Option c is the easiest to test that I have correctly identified the problem.

**Comment by p-1603** [comment]
I've been trying to test this, but have been somewhat hampered by OpenStack connectivity problems. The SSH handshake required to authenticate and build a custom image is constantly failing, meaning I can't try the options above. I am speaking to OVH support and will keep you updated.

However, I reasoned that since the custom image was only there to enable SELinux, and since SELinux appears to be enabled, that I didn't really need it.

Using the base "Centos 7" image though, I find the problem persists. I can only SSH into the cluster for a brief period.

**Comment by cmd-ntrf** [comment]
Can you verify the path of the home folder of the `centos` account when your first login and post it here?

**Comment by p-1603** [comment]
Hello, I've managed to get the authentication sorted, and have created a cluster using a new `sudoer_username` as above. Some updates:

- The sudoer account (`alex`) now stays accessible, and is located at `/alex`.
- The `centos` account does not appear to have a home directory (`echo ~$centos` just returns `~`).
- I cannot get into the `admin` account at all. The password is demanded, but is not accepted.
- The guest user accounts still work fine.
- I cannot get into the management node, which still asks for a password. I'm assuming I should be able to SSH straight into that, and not use a proxy jump or anything.

**Comment by cmd-ntrf** [comment]
> * The sudoer account (`alex`) now stays accessible, and is located at `/alex`.

This confirms the theory that user `centos` home is probably under `/home` and being shadowed by NFS.

> * The `centos` account does not appear to have a home directory (`echo ~$centos` just returns `~`).

You can retrieve the home directory of user `centos` with the following command:
```
getent passwd centos
```

> * I cannot get into the `admin` account at all. The password is demanded, but is not accepted.

The admin account is only usable with FreeIPA CLI or web interface. You cannot login with `admin` in SSH.

> * The guest user accounts still work fine.

Good.

> * I cannot get into the management node, which still asks for a password. I'm assuming I should be able to SSH straight into that, and not use a proxy jump or anything.

To access the management node, you need to either use a proxy jump or configure your ssh-agent and activate SSH agent forwarding when connecting to the login node.

**Comment by p-1603** [comment]
```
$ getent passwd centos
centos:x:1000:1000:Cloud User:/home/centos:/bin/bash
```
It seems you are right.

I didn't realise that for the admin account. I had a go at a proxy jump for the management node, but didn't have any luck. Is the account name the same as the sudoer, and accessed via the sudoer on the login node?

**Comment by cmd-ntrf** [comment]
Yes, the sudoer account is configured on every node of the cluster. So you should be able to do : `ssh alex@mgmt1` from login1 if you have ssh agent forwarding activated.

**Comment by p-1603** [comment]
Hello. Thank you for the replies, and sorry for not replying over the weekend.

I have tried setting up a proxy jump from my local machine, and also reaching `mgmt1` from `login1` as you suggest. Both times I am asked for a password. That doesn't seem right?

**Comment by cmd-ntrf** [comment]
You should be able to login using the sudoer account on all nodes of the cluster using a proxy jump or ssh agent forwarding.

When using OVH, `mgmt1` is assigned a public ip address. You could edit the network security groups and allow SSH access on mgmt1 from the Internet and try logging in directly with its public ip instead of the proxy jump. If it works, there is problem with your proxy configuration. If it doesn't, something is wrong with the sudoer account configuration on mgmt1.

**Comment by p-1603** [comment]
Hello. Yesterday I rebuilt my cluster to see whether I could log in straight after cluster creation, and whether the problem appeared later as with the login node. I found recreating the cluster seems to have fixed the problem, and I have been able to use it today also with no issues, so everything seems to be working.

Thank you both for all your help.
