### ISSUE TITLE
Deprecated SHA1 SSHFP records should be removed

### ISSUE THREAD

**Issue by jflandry** [ComputeCanada/magic_castle#22]
SHA1 signatures have been deprecated for years and have been practically broken. Only SHA256 SSHFP records should be registered in DNS.

https://blog.qualys.com/ssllabs/2014/09/09/sha1-deprecation-what-you-need-to-know
https://shattered.io/

In practice, delete the
```
resource "cloudflare_record" "loginX_sshfp_rsa_sha1" {}
```
block from the cloudflare DNS provider.

**Comment by cmd-ntrf** [comment]
We should also remove lined related to sha1 from `key2fp.py`.

**Comment by cmd-ntrf** [comment]
Thanks! Fixed in commit 3b87ce933c4218cf69dd4dae8705e008f82c08a3
