### ISSUE TITLE
Support confirmation/check that the resources are fully deployed and usable

### ISSUE THREAD

**Issue by ccoulombe** [ComputeCanada/magic_castle#25]
When running `terraform apply` it would be useful to know when the resources are fully deployed.

A timeout of N minutes could do the trick but a better way would be to have some kind of hook that triggers when deployment and setup are complete.

**Comment by cmd-ntrf** [comment]
We could configure a postruncommand in puppet.conf:
https://puppet.com/docs/puppet/5.5/configuration.html#postruncommand

**Comment by cmd-ntrf** [comment]
Fixed in https://github.com/ComputeCanada/puppet-magic_castle/commit/83ddbb18b23373c46003ad1627224f22f473f03f
