### ISSUE TITLE
Terraform runs do not include all node names with auto-scaling

### ISSUE THREAD

**Issue by mboisson** [ComputeCanada/magic_castle#265]
It sometimes happen that the Terraform.IO runs do not include the names of all nodes when it runs. 

For example, a run titled `Slurm suspend nodepoolgpu1` actually suspended both `nodepoolgpu1` and `nodepoolgpu2` 

I *think* it only happens with suspend, not with resume.

**Comment by cmd-ntrf** [comment]
The issue arises when [slurm-autoscale-tfe](https://www.github.com/magiccastle/slurm-autoscale-tfe) detects a drift between Slurm compute node inventory and the pool variable in Terraform cloud. If an instance is missing from Slurm's state, but present in the pool variable, the autoscale script will remove it.

This situation can happen during resume and suspend. Currently the drift detection and its resulting action is only logged in `/var/log/slurm/slurm_autoscale.log`, but it should also be part of the message - or constitute a separate apply with the appropriate message.
