### ISSUE TITLE
Add and remove nodes with arbirtrary extention number

### ISSUE THREAD

**Issue by poquirion** [ComputeCanada/magic_castle#311]
I would like to be able to select node number to be added and especially removed from a MC cluster. Let say I have five compute nodes defined in `main.tf` like this:

```
node-   = { type = "c4-24gb-80", tags = ["node"], count = 5 }
```
I have no way of removing  `node-2` only. Perhaps one of these notations could be supported: 

```
node-   = { type = "c4-24gb-80", tags = ["node"], count = [1,3,4,5] }
node-   = { type = "c4-24gb-80", tags = ["node"], count = ["1","3-5"] }
node-   = { type = "c4-24gb-80", tags = ["node"], count = "1,3-5" }
```

**Comment by cmd-ntrf** [comment]
Add the `"pool"` tag to your compute node and use the pool variable : 
https://github.com/ComputeCanada/magic_castle/tree/main/docs#419-pool-optional

```
node-   = { type = "c4-24gb-80", tags = ["node", "pool"], count = 5 }
pool = ["node-1", "node-3", "node-4", "node-5"]
```

The variable is normally handled by Slurm through an API, but since you are manually scaling the resources, you can defined pool manually.
