### ISSUE TITLE
Error when destroying clusters on GCP

### ISSUE THREAD

**Issue by verdurin** [ComputeCanada/magic_castle#48]
(Apologies for the flurry of issues...hopefully they're useful)

This evening I've found that after a while (an hour or so) I am unable to connect to the clusters created with Magic  Castle. Hence I have been destroying them and building new ones.

When I destroy them, it fails with several errors at the first attempt, then with this one at the second attempt:
```
Error: Invalid index

  on gcp/outputs.tf line 26, in output "guest_passwd":
  26:   value = var.guest_passwd != "" ? var.guest_passwd : random_pet.guest_passwd[0].id
    |----------------
    | random_pet.guest_passwd is empty tuple

The given key does not identify an element in this collection value.
```

**Comment by cmd-ntrf** [comment]
You said you cannot connect to the cluster after a while. This is abnormal, but not unheard of. It has been reported to me directly that GCP instances sometime drop their network interface for unknown reason and require a reboot.

If it happens again, try rebooting the instances with the GCP cli or web ui.

**Comment by verdurin** [comment]
Useful to know, thanks. Will try that with the next one (currently building).

**Comment by cmd-ntrf** [comment]
Regarding the destroy, next time try :
```
terraform destroy -refresh=false
```

With this flag, terraform should not try to refresh the state and be able to go further in its destroy process. This has been added to the documentation recently. If it does not help, let me know more about the error on the first destroy.

**Comment by verdurin** [comment]
Ah, indeed, did see that in the changelog. Will try if it re-occurs.

**Comment by verdurin** [comment]
In case other people see this, example logs from the management node when there are connectivity problems:
```
Feb 17 03:01:48 mgmt1 named-pkcs11[9511]: network unreachable resolving 'metadata.google.internal/A/IN': 169.254.169.254#53
Feb 17 03:01:48 mgmt1 named-pkcs11[9511]: network unreachable resolving 'metadata.google.internal/AAAA/IN': 169.254.169.254#53
Feb 17 03:01:48 mgmt1 consul: 2020/02/17 03:01:48 [WARN] consul: error getting server health from "mgmt1": rpc error getting client: failed to get conn: dial tcp <nil>->10.0.0.2:8300: connect: network is unreachable
Feb 17 03:01:49 mgmt1 consul: 2020/02/17 03:01:49 [WARN] consul: error getting server health from "mgmt1": context deadline exceeded
```

**Comment by cmd-ntrf** [comment]
The networking issue that initiated the destroy has been fixed. See #50.
