### ISSUE TITLE
[gcp] Ability to create more than one cluster using the same provider

### ISSUE THREAD

**Issue by verdurin** [ComputeCanada/magic_castle#49]
If I try to create more than one cluster on GCP I see errors owing to name clashes:
```
rror: Error creating Disk: googleapi: Error 409: The resource 'projects/<project>/zones/europe-west2-c/disks/home' already exists, alreadyExists

  on gcp/infrastructure.tf line 36, in resource "google_compute_disk" "home":
  36: resource "google_compute_disk" "home" {



Error: Error creating Disk: googleapi: Error 409: The resource 'projects/<project>/zones/europe-west2-c/disks/project' already exists, alreadyExists

  on gcp/infrastructure.tf line 44, in resource "google_compute_disk" "project":
  44: resource "google_compute_disk" "project" {



Error: Error creating Disk: googleapi: Error 409: The resource 'projects/<project>/zones/europe-west2-c/disks/scratch' already exists, alreadyExists

  on gcp/infrastructure.tf line 52, in resource "google_compute_disk" "scratch":
  52: resource "google_compute_disk" "scratch" {



Error: Error creating Address: googleapi: Error 409: The resource 'projects/<project>/regions/europe-west2/addresses/login1-ipv4' already exists, alreadyExists

  on gcp/infrastructure.tf line 127, in resource "google_compute_address" "static":
 127: resource "google_compute_address" "static" {
```

The potential use-case here is for groups from the same community who may need similar clusters but they must not be able to see each others' datasets and generated data. This would be one way of achieving that.

**Comment by cmd-ntrf** [comment]
The solution for the instances was to prefix the name of the resource with the name of the cluster. I thought we had done this for every resource, but apparently [I only did it for the instances](https://github.com/ComputeCanada/magic_castle/commit/4971cb47c97b98cb179ca1a59cb1248667a2655b).

This is only a problem for GCP. OpenStack, AWS and Azure do not care if multiple resource have the same name since they also have a UUID.

**Comment by cmd-ntrf** [comment]
Commit 78acb54c6964e519dfa56b55e695e0e28c0112df completes make the resources in GCP named after their cluster. Therefore, as long as the cluster_name are different, it should now be possible to spawn multiple cluster in the same project.
