### ISSUE TITLE
How to test?

### ISSUE THREAD

**Issue by verdurin** [ComputeCanada/magic_castle#57]
Is there a documented way of generating new releases so I can test the latest fixes?

Naively running `release.sh 5.8` spewed out lots of errors, though it did create some output files.

**Comment by verdurin** [comment]
I see there are some related comments at https://github.com/ComputeCanada/magic_castle/blob/master/docs/developers.md

**Comment by cmd-ntrf** [comment]
You can use the examples from github directly. Their source for the Terraform modules and the Puppet modules are the git repo master branch.

**Comment by verdurin** [comment]
Yes, this works nicely, thanks.

**Comment by cmd-ntrf** [comment]
I have added this to the list of developper doc todos.
