### ISSUE TITLE
Q: Is it possible to use the Google Cloud DNS provider with another cloud provider?

### ISSUE THREAD

**Issue by verdurin** [ComputeCanada/magic_castle#64]
It would be very convenient if I could use the excellent integration with Google's Cloud DNS, even when the actual compute resources are held elsewhere.

Would that just be a matter of copying the relevant code from the `gcp` instance of the `dns` module into the appropriate directory?

**Comment by cmd-ntrf** [comment]
Yes, just a matter of copying the gcloud module in another provider example.

The gcloud dns example is part of openstack and gcp, but you could use it with Azure, AWS and OVH. It it just a matter of copying the module and renaming the provider output variables that are used as input for the gcloud dns module.

**Comment by cmd-ntrf** [comment]
I just added the gcloud dns module to the examples where it was missing
https://github.com/ComputeCanada/magic_castle/commit/817b59b52eeecd1a314bafdaf340511720fe7b06

**Comment by verdurin** [comment]
This works perfectly in my testing with `aws`.
