### ISSUE TITLE
Documentation references out of date

### ISSUE THREAD

**Issue by cgeroux** [ComputeCanada/magic_castle#66]
Section 4.5 references sections 9.3 and 9.4 (which don't exist) but looks like sections 10.3 and 10.4 which do exist covers the material discussed in sections 4.5. Should be a simple matter of updating the references to point the correct section.

The particular file in question is: https://github.com/ComputeCanada/magic_castle/tree/master/docs/README.md as seen on commit 5ab624227489dc42567634a25999a31037df2297

**Comment by cmd-ntrf** [comment]
Thanks! Fixed in a7e79ce6f814cb6fefab6d2665881c3869fdaeb1
