### ISSUE TITLE
Ability to specify volume types

### ISSUE THREAD

**Issue by verdurin** [ComputeCanada/magic_castle#67]
As a stopgap before other storage types such as Lustre are available, it would be very handy to be able to specify the volume types for a cluster e.g. different types of SSD on `aws`. I have a draft PR to accomplish this, if it would be useful.

**Comment by cmd-ntrf** [comment]
I am currently working on refactoring the storage parts, so it's good time to send the draft and start a discussion on the best design to support different volume types.

**Comment by poquirion** [comment]
Same thing here, we do not have much problems with the reduce load design in workshop, but IO has been a problems for _real_ bioiofo data.

@arshul doing a prototype for a terraform deployed beeGFS cluster. Once it is reasonably polished and we get better feel on how it works we could try to add it here. 

We would put the metadata service on the mgmt node.
The first step could be to have pure storage nodes doing the storage service and then to be able to register compute node with local drive to be part of the storage service.  

The interface in main.tf could look like 

  instances = {
    storage  = { type = "c1-7.5gb-30", count = 10 },  # 10 pure storage nodes
    mgmt  = { type = "p8-12gb", count = 1 },
    login = { type = "p2-3gb", count = 1 },
    node  = [ { type = "c8-30gb-186", count = 3, localdisk_storage_fration=0.8 }, # 80% of the local disks are used for the storage service      
    ]
  }

  storage = {
    home = { type  = "nfs", size    = 4000}
    project = { type  = "nfs",  size = 1000 }
    scratch = {type  = "beeGFS",  size = 0  } # 0 --> get everything available in beeGFS.
  }

**Comment by cmd-ntrf** [comment]
It took me some time, but I now have a draft that allow the specification of storage type.

It currently is functional for AWS and OpenStack:
https://github.com/ComputeCanada/magic_castle/pull/150

Feedback is welcomed.
