### ISSUE TITLE
AWS device names incorrect/redundant?

### ISSUE THREAD

**Issue by jeromekelleher** [ComputeCanada/magic_castle#75]
In the AWS infrastructure.tf files,  there is a ``device_name`` attribute in the ``home``, ``project`` and ``scratch`` resources, e.g.,

https://github.com/ComputeCanada/magic_castle/blob/cf1adeb04877304200270b846f84fce2c6fa53ff/aws/infrastructure.tf#L208-L214

These are given devices /dev/sdb, etc, but the actual block devices on the realised mgmt1 node are ``/dev/nvme1n1``, etc.  

It would be straightforward to change the block device names, but since they don't appear to be doing anything much, perhaps it would be better to remove them?

(cc @verdurin - let me know if you think this is a quirk of our own setup and I'll close the issue)

**Comment by cmd-ntrf** [comment]
From [AWS documentation](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/nvme-ebs-volumes.html)
> EBS volumes are exposed as NVMe block devices on Nitro-based instances.
and
> The following instances are based on the Nitro system:
> A1, C5, C5d, C5n, G4, I3en, Inf1, M5, M5a, M5ad, M5d, M5dn, M5n, p3dn.24xlarge, R5, R5a, R5ad, R5d, R5dn, R5n, T3, T3a, and z1d

For non-Nitro-based instances, the device_name parameter is used. That said, we no longer have a use for the device name parameter, so it could be removed but there is no harm in keeping it either.

**Comment by jeromekelleher** [comment]
Ah, so we're seeing the nvme devices because we're on a nitro system. Thanks.
