### ISSUE TITLE
Add singularity 

### ISSUE THREAD

**Issue by poquirion** [ComputeCanada/magic_castle#99]
Install singularity on compute and login nodes.

Have a single location to store the images.

**Comment by cmd-ntrf** [comment]
Singularity is already installed in `/opt/software/singularity` and loadable with `module load singularity`.
Am I missing something?

**Comment by poquirion** [comment]
Nope. it seems that I am the one missing something :grimacing:

**Comment by poquirion** [comment]
But then the other part of the issue is still there, do we have a central storage for the container? That could be useful for a workshop that uses singularity.

**Comment by cmd-ntrf** [comment]
Storing containers on CVMFS has been discussed a few times internally, but I don't think there has been any progress. 

The question could be asked on this repo: https://github.com/ComputeCanada/software-stack
